version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly" # Checks weekly for updates
    commit-message:
      # Prefixes all commit messages with "package: "
      prefix: "package:"
