name: Badge Request
description: Request a badge that you would like to see be added to the current badge list.
title: "[Badge Request]: "
labels: ["badge request"]
projects: ["inttter/mdbadges-cli"]
assignees:
  - inttter
body:
  - type: markdown
    attributes:
      value: |
        Make sure the badge does not **already exist** in this repository. Preferably, it should also have a logo associated with it on [SimpleIcons](https://simpleicons.org) simplify the process of adding it.
  - type: input
    id: name
    attributes:
      label: Badge Name
      description: What is the name of the badge?
      placeholder: eg. React
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description about who/what the badge is for. For example, you can link a URL to a website.
      placeholder: This badge is for [NAME].
    validations:
      required: true