name: Issue Report
description: Report a bug in the package.
title: "[Bug]: "
labels: ["bug"]
projects: ["inttter/mdbadges-cli"]
body:
  - type: markdown
    attributes:
      value: |
        Search for your issue in the [issue listing](https://github.com/inttter/mdbadges-cli/issues) to make sure your issue is not a duplicate.
  - type: input
    attributes:
      label: Version
      description: The version this bug was encountered on.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description of issue
      description: Describe the issue and provide any additional details, such as console outputs or error messages.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots/Videos
      description: If applicable, drag a screenshot or video into this box that shows this issue.
    validations:
      required: false