const badges = {
    'app-store': {
        'app-store': '[![App Store](https://img.shields.io/badge/App_Store-0D96F6?logo=app-store&logoColor=white)](#) ',
        'play-store': '[![Google Play Store](https://img.shields.io/badge/Google_Play-414141?logo=google-play&logoColor=white)](#)'
    },
    'ai': {
        'amazon-alexa': '[![Amazon Alexa](https://img.shields.io/badge/Amazon%20Alexa-00CAFF?logo=amazonalexa&logoColor=fff)](#) ',
        'chatgpt': '[![ChatGPT](https://img.shields.io/badge/ChatGPT-74aa9c?logo=openai&logoColor=white)](#) ',
        'dependabot': '[![Dependabot](https://img.shields.io/badge/Dependabot-025E8C?logo=dependabot&logoColor=fff)](#) ',
        'google-assistant': '[![Google Assistant](https://img.shields.io/badge/Google%20Assistant-4285F4?logo=googleassistant&logoColor=fff)](#) ',
        'google-bard': '[![Google Bard](https://img.shields.io/badge/Google%20Bard-886FBF?logo=googlebard&logoColor=fff)](#) ',
        'renovatebot': '[![RenovateBot](https://img.shields.io/badge/RenovateBot-1A1F6C?logo=renovatebot&logoColor=fff)](#) '
    },
    'blog': {
        'blogger': '[![Blogger](https://img.shields.io/badge/Blogger-%23FF5722.svg?logo=blogger&logoColor=white)](#) ',
        'dev-to': '[![Dev.to](https://img.shields.io/badge/Dev.to-0A0A0A?logo=devdotto&logoColor=white)](#) ',
        'geeks-for-geeks': '[![GeeksForGeeks](https://img.shields.io/badge/GeeksforGeeks-298D46?logo=geeksforgeeks&logoColor=white)](#) ',
        'ghost': '[![Ghost](https://img.shields.io/badge/Ghost-000?logo=ghost&logoColor=yellow)](#) ',
        'hashnode': '[![Hashnode](https://img.shields.io/badge/Hashnode-2962FF?logo=hashnode&logoColor=white)](#) ',
        'medium': '[![Medium](https://img.shields.io/badge/Medium-%23000000.svg?logo=medium&logoColor=white)](#) ',
        'mastodon': '[![Mastodon](https://img.shields.io/badge/Mastodon-6364FF?logo=mastodon&logoColor=fff)](#) ',
        'rss': '[![RSS](https://img.shields.io/badge/RSS-FFA500?logo=rss&logoColor=white)](#) ',
        'squarespace': '[![Squarespace](https://img.shields.io/badge/Squarespace-000000?logo=squarespace&logoColor=fff)](#) ',
        'substack': '[![Substack](https://img.shields.io/badge/Substack-FF6719?logo=substack&logoColor=fff)](#) ',
        'tumblr': '[![Tumblr](https://img.shields.io/badge/Tumblr-%2336465D.svg?logo=tumblr&logoColor=white)](#) ',
        'wix': '[![Wix](https://img.shields.io/badge/Wix-%23000000.svg?logo=wix&logoColor=white)](#) ',
        'wordpress': '[![WordPress](https://img.shields.io/badge/WordPress-%2321759B.svg?logo=wordpress&logoColor=white)](#) '
    },
    'browser': {
        'arc': '[![Arc](https://img.shields.io/badge/Arc-FCBFBD?logo=arc&logoColor=000)](#) ',
        'brave': '[![Brave](https://img.shields.io/badge/Brave-FB542B?logo=Brave&logoColor=white)](#) ',
        'chrome': '[![Google Chrome](https://img.shields.io/badge/Google%20Chrome-4285F4?logo=GoogleChrome&logoColor=white)](#) ',
        'edge': '[![Edge](https://img.shields.io/badge/Edge-0078D7?logo=Microsoft-edge&logoColor=white)](#) ',
        'firefox': '[![Firefox](https://img.shields.io/badge/Firefox-FF7139?logo=Firefox&logoColor=white)](#) ',
        'ie': '[![IE](https://img.shields.io/badge/Internet%20Explorer-0076D6?logo=Internet%20Explorer&logoColor=white)](#) ',
        'opera': '[![Opera](https://img.shields.io/badge/Opera-FF1B2D?logo=Opera&logoColor=white)](#) ',
        'safari': '[![Safari](https://img.shields.io/badge/Safari-006CFF?logo=safari&logoColor=fff)](#) ',
        'tor': '[![Tor](https://img.shields.io/badge/Tor-7D4698?logo=Tor-Browser&logoColor=white)](#) ',
        'vivaldi': '[![Vivaldi](https://img.shields.io/badge/Vivaldi-EF3939?logo=Vivaldi&logoColor=white)](#) '
    },
    'ci': {
        'appveyor': '[![AppVeyor](https://img.shields.io/badge/AppVeyor-00B3E0?logo=appveyor&logoColor=fff)](#) ',
        'azure-pipelines': '[![Azure Pipelines](https://img.shields.io/badge/Azure%20Pipelines-2560E0?logo=azurepipelines&logoColor=fff)](#) ',
        'bamboo': '[![Bamboo](https://img.shields.io/badge/Bamboo-0052CC?logo=bamboo&logoColor=fff)](#) ',
        'bitbucket-pipelines': '[![Bitbucket Pipelines](https://img.shields.io/badge/Bitbucket_Pipelines-0052CC?logo=bitbucket&logoColor=white)](#) ',
        'circleci': '[![CircleCI](https://img.shields.io/badge/CircleCI-343434?logo=circleci&logoColor=fff)](#) ',
        'github-actions': '[![GitHub Actions](https://img.shields.io/badge/GitHub_Actions-2088FF?logo=github-actions&logoColor=white)](#) ',
        'gitlab-ci': '[![GitLab CI](https://img.shields.io/badge/GitLab%20CI-FC6D26?logo=gitlab&logoColor=fff)](#) ',
        'jenkins': '[![Jenkins](https://img.shields.io/badge/Jenkins-D24939?logo=jenkins&logoColor=white)](#) ',
        'semaphore': '[![Semaphore](https://img.shields.io/badge/Semaphore-19A974?logo=semaphoreci&logoColor=fff)](#) ',
        'travis-ci': '[![Travis CI](https://img.shields.io/badge/Travis%20CI-3EAAAF?logo=travisci&logoColor=fff)](#) '
    },
    'cloud-storage': {
        'box': '[![Box](https://img.shields.io/badge/Box-0061D5?logo=box&logoColor=fff)](#) ',
        'dropbox': '[![Dropbox](https://img.shields.io/badge/Dropbox-0061FF?logo=dropbox&logoColor=fff)](#) ',
        'google-drive': '[![Google Drive](https://img.shields.io/badge/Google%20Drive-4285F4?logo=googledrive&logoColor=fff)](#) ',
        'mega': '[![Mega](https://img.shields.io/badge/Mega-%23D90007.svg?logo=mega&logoColor=white)](#) ',
        'onedrive': '[![Microsoft OneDrive](https://img.shields.io/badge/Microsoft%20OneDrive-0078D4?logo=microsoftonedrive&logoColor=fff)](#) ',
        'proton-drive': '[![Proton Drive](https://img.shields.io/badge/Proton%20Drive-6d4aff?logo=proton%20drive&logoColor=white)](#) '
    },
    'cloud-system': {
        'alibaba-cloud': '[![Alibaba Cloud](https://img.shields.io/badge/AlibabaCloud-%23FF6701.svg?logo=alibabacloud&logoColor=white)](#) ',
        'aws': '[![AWS](https://img.shields.io/badge/AWS-%23FF9900.svg?logo=amazon-aws&logoColor=white)](#) ',
        'azure': '[![Azure](https://img.shields.io/badge/Azure-%230072C6.svg?logo=microsoftazure&logoColor=white)](#) ',
        'azure-devops': '[![Azure DevOps](https://img.shields.io/badge/Azure%20DevOps-0078D7?logo=azuredevops&logoColor=fff)](#) ',
        'cloudflare': '[![Cloudflare](https://img.shields.io/badge/Cloudflare-F38020?logo=Cloudflare&logoColor=white)](#) ',
        'digitalocean': '[![DigitalOcean](https://img.shields.io/badge/DigitalOcean-%230167ff.svg?logo=digitalOcean&logoColor=white)](#) ',
        'docker': '[![Docker](https://img.shields.io/badge/Docker-2496ED?logo=docker&logoColor=fff)](#) ',
        'firebase': '[![Firebase](https://img.shields.io/badge/Firebase-039BE5?logo=Firebase&logoColor=white)](#) ',
        'github-pages': '[![Github Pages](https://img.shields.io/badge/Github%20Pages-121013?logo=github&logoColor=white)](#) ',
        'gitlab': '[![GitLab](https://img.shields.io/badge/GitLab-FC6D26?logo=gitlab&logoColor=fff)](#) ',
        'google-cloud': '[![Google Cloud](https://img.shields.io/badge/Google%20Cloud-%234285F4.svg?logo=google-cloud&logoColor=white)](#) ',
        'heroku': '[![Heroku](https://img.shields.io/badge/Heroku-430098?logo=heroku&logoColor=fffe)](#) ',
        'ibm-cloud': '[![IBM Cloud](https://img.shields.io/badge/IBM%20Cloud-1261FE?logo=ibmcloud&logoColor=fff)](#) ',
        'jenkins': '[![Jenkins](https://img.shields.io/badge/Jenkins-D24939?logo=jenkins&logoColor=fff)](#) ',
        'kubernetes': '[![Kubernetes](https://img.shields.io/badge/Kubernetes-326CE5?logo=kubernetes&logoColor=fff)](#) ',
        'netlify': '[![Netlify](https://img.shields.io/badge/Netlify-%23000000.svg?logo=netlify&logoColor=#00C7B7)](#) ',
        'octopus-deploy': '[![Octopus Deploy](https://img.shields.io/badge/Octopus%20Deploy-2F93E0?logo=Octopus%20Deploy&logoColor=white)](#) ',
        'oracle': '[![Oracle](https://img.shields.io/badge/Oracle%20Cloud-F80000?logo=oracle&logoColor=white)](#) ',
        'sap': '[![SAP](https://img.shields.io/badge/SAP-0FAAFF?logo=sap&logoColor=fff)](#) ',
        'salesforce': '[![Salesforce](https://img.shields.io/badge/Salesforce-00A1E0?logo=salesforce&logoColor=fff)](#) ',
        'vercel': '[![Vercel](https://img.shields.io/badge/Vercel-%23000000.svg?logo=vercel&logoColor=white)](#) '
    },
    'code-coverage': {
        'codecov': '[![Codecov](https://img.shields.io/badge/Codecov-F01F7A?logo=codecov&logoColor=fff)](#) ',
        'code-climate': '[![Code Climate](https://img.shields.io/badge/Code%20Climate-000?logo=codeclimate&logoColor=fff)](#) ',
        'codacy': '[![Codacy](https://img.shields.io/badge/Codacy-222F29?logo=codacy&logoColor=fff)](#) ',
        'coveralls': '[![Coveralls](https://img.shields.io/badge/Coveralls-3F5767?logo=coveralls&logoColor=fff)](#) ',
        'sonarcloud': '[![SonarCloud](https://img.shields.io/badge/SonarCloud-F3702A?logo=sonarcloud&logoColor=fff)](#) ',
        'snyk': '[![Snyk](https://img.shields.io/badge/Snyk-4C4A73?logo=snyk&logoColor=fff)](#) '
    },
    'code-editor': {
        'codepen': '[![CodePen](https://img.shields.io/badge/CodePen-white?&logo=codepen&logoColor=black)](#) ',
        'eclipse': '[![Eclipse](https://img.shields.io/badge/Eclipse-FE7A16.svg?logo=Eclipse&logoColor=white)](#) ',
        'emacs': '[![Emacs](https://img.shields.io/badge/Emacs-%237F5AB6.svg?&logo=gnu-emacs&logoColor=white)](#) ',
        'intellij-idea': '[![IntelliJ IDEA](https://img.shields.io/badge/IntelliJIDEA-000000.svg?logo=intellij-idea&logoColor=white)](#) ',
        'netbeans-ide': '[![NetBeans IDE](https://img.shields.io/badge/NetBeans%20IDE-1B6AC6.svg?logo=apache-netbeans-ide&logoColor=white)](#) ',
        'neovim': '[![Neovim](https://img.shields.io/badge/Neovim-57A143?logo=neovim&logoColor=fff)](#) ',
        'notepad-pp': '[![Notepad++](https://img.shields.io/badge/Notepad++-90E59A.svg?&logo=notepad%2b%2b&logoColor=black)](#) ',
        'obsidian': '[![Obsidian](https://img.shields.io/badge/Obsidian-%23483699.svg?&logo=obsidian&logoColor=white)](#) ',
        'pycharm': '[![PyCharm](https://img.shields.io/badge/PyCharm-143?logo=pycharm&logoColor=black&color=black&labelColor=green)](#) ',
        'python-idle': '[![Python IDLE](https://img.shields.io/badge/Python%20IDLE-3776AB?logo=python&logoColor=fff)](#) ',
        'replit': '[![Replit](https://img.shields.io/badge/Replit-F26207?logo=replit&logoColor=fff)](#) ',
        'sublime-text': '[![Sublime Text](https://img.shields.io/badge/Sublime%20Text-%23575757.svg?logo=sublime-text&logoColor=important)](#) ',
        'vim': '[![Vim](https://img.shields.io/badge/Vim-%2311AB00.svg?logo=vim&logoColor=white)](#) ',
        'visual-studio': '[![Visual Studio](https://img.shields.io/badge/Visual%20Studio-5C2D91.svg?&logo=visual-studio&logoColor=white)](#) ',
        'vscode': '[![Visual Studio Code](https://img.shields.io/badge/Visual%20Studio%20Code-0078d7.svg?logo=visual-studio-code&logoColor=white)](#) ',
        'vscodium': '[![VSCodium](https://img.shields.io/badge/VSCodium-2F80ED?logo=vscodium&logoColor=fff)](#) ',
        'xcode': '[![Xcode](https://img.shields.io/badge/Xcode-007ACC?logo=Xcode&logoColor=white)](#) '
    },
    'collaboration': {
        'asana': '[![Asana](https://img.shields.io/badge/Asana-F06A6A?logo=asana&logoColor=fff)](#) ',
        'jira': '[![Jira](https://img.shields.io/badge/Jira-0052CC?logo=jira&logoColor=fff)](#) ',
        'microsoft-teams': '[![Microsoft Teams](https://img.shields.io/badge/Microsoft%20Teams-6264A7?logo=microsoftteams&logoColor=fff)](#) ',
        'slack': '[![Slack](https://img.shields.io/badge/Slack-4A154B?logo=slack&logoColor=fff)](#) ',
        'trello': '[![Trello](https://img.shields.io/badge/Trello-0052CC?logo=trello&logoColor=fff)](#) '
    },
    'crypto': {
        'bitcoin': '[![Bitcoin](https://img.shields.io/badge/Bitcoin-FF9900?logo=bitcoin&logoColor=white)](#) ',
        'bitcoin-cash': '[![Bitcoin Cash](https://img.shields.io/badge/Bitcoin%20Cash-0AC18E?logo=bitcoincash&logoColor=fff)](#) ',
        'bitcoin-sv': '[![Bitcoin SV](https://img.shields.io/badge/Bitcoin%20SV-EAB300?logo=bitcoinsv&logoColor=fff)](#) ',
        'cardano': '[![Cardano](https://img.shields.io/badge/Cardano-0E4D92?logo=cardano&logoColor=white)](#) ',
        'chainlink': '[![Chainlink](https://img.shields.io/badge/Chainlink-2A5ADA?logo=chainlink&logoColor=white)](#) ',
        'dogecoin': '[![Dogecoin](https://img.shields.io/badge/Dogecoin-C2A633?logo=dogecoin&logoColor=white)](#) ',
        'ethereum': '[![Ethereum](https://img.shields.io/badge/Ethereum-3C3C3D?logo=ethereum&logoColor=white)](#) ',
        'litecoin': '[![Litecoin](https://img.shields.io/badge/Litecoin-A6A9AA?logo=litecoin&logoColor=white)](#) ',
        'polkadot': '[![Polkadot](https://img.shields.io/badge/Polkadot-E6007A?logo=polkadot&logoColor=white)](#) ',
        'ripple': '[![Ripple](https://img.shields.io/badge/Ripple-2288CB?logo=ripple&logoColor=white)](#) ',
        'stellar': '[![Stellar](https://img.shields.io/badge/Stellar-7D00FF?logo=stellar&logoColor=fff)](#) ',
        'tether': '[![Tether](https://img.shields.io/badge/Tether-168363?&logo=tether&logoColor=white)](#) '
    },
    'database': {
        'arangodb': '[![ArangoDB](https://img.shields.io/badge/ArangoDB-DDE072?logo=arangodb&logoColor=000)](#) ',
        'cassandra': '[![Cassandra](https://img.shields.io/badge/Cassandra-%231287B1.svg?logo=apache-cassandra&logoColor=white)](#) ',
        'couchbase': '[![Couchbase](https://img.shields.io/badge/Couchbase-EA2328?logo=couchbase&logoColor=white)](#) ',
        'dynamodb': '[![DynamoDB](https://img.shields.io/badge/DynamoDB-4053D6?logo=amazondynamodb&logoColor=fff)](#) ',
        'firebase': '[![Firebase](https://img.shields.io/badge/Firebase-039BE5?logo=Firebase&logoColor=white)](#) ',
        'influxdb': '[![InfluxDB](https://img.shields.io/badge/InfluxDB-22ADF6?logo=influxdb&logoColor=fff)](#) ',
        'mariadb': '[![MariaDB](https://img.shields.io/badge/MariaDB-003545?logo=mariadb&logoColor=white)](#) ',
        'mssqlserver': '[![Microsoft SQL Server](https://img.shields.io/badge/Microsoft%20SQL%20Server-CC2927?logo=microsoft%20sql%20server&logoColor=white)](#) ',
        'mongodb': '[![MongoDB](https://img.shields.io/badge/MongoDB-%234ea94b.svg?logo=mongodb&logoColor=white)](#) ',
        'mysql': '[![MySQL](https://img.shields.io/badge/MySQL-4479A1?logo=mysql&logoColor=fff&)](#) ',
        'neo4j': '[![Neo4J](https://img.shields.io/badge/Neo4j-008CC1?logo=neo4j&logoColor=white)](#) ',
        'oracle': '[![Oracle](https://img.shields.io/badge/Oracle-F80000?logo=oracle&logoColor=fff)](#) ',
        'postgres': '[![Postgres](https://img.shields.io/badge/Postgres-%23316192.svg?logo=postgresql&logoColor=white)](#) ',
        'redis': '[![Redis](https://img.shields.io/badge/Redis-%23DD0031.svg?logo=redis&logoColor=white)](#) ',
        'sqlite': '[![SQLite](https://img.shields.io/badge/SQLite-%2307405e.svg?logo=sqlite&logoColor=white)](#) ',
        'teradata': '[![Teradata](https://img.shields.io/badge/Teradata-F37440?logo=teradata&logoColor=fff)](#) '
    },
    'delivery': {
        'deliveroo': '[![Deliveroo](https://img.shields.io/badge/Deliveroo-00CCBC?logo=Deliveroo&logoColor=white)](#) ',
        'doordash': '[![Doordash](https://img.shields.io/badge/DoorDash-FF3008?logo=DoorDash&logoColor=white)](#) ',
        'grubhub': '[![GrubHub](https://img.shields.io/badge/Grubhub-F63440?logo=Grubhub&logoColor=white)](#) ',
        'just-eat': '[![Just Eat](https://img.shields.io/badge/Just%20Eat-F36D00?logo=justeat&logoColor=fff)](#) ',
        'uber-eats': '[![Uber Eats](https://img.shields.io/badge/Uber_Eats-5FB709?logo=uber-eats&logoColor=white)](#) '
    },
    'design': {
        'after-effects': '[![Adobe After Effects](https://img.shields.io/badge/Adobe%20After%20Effects-CF96FD?logo=Adobe%20After%20Effects&logoColor=393665)](#) ',
        'behance': '[![Behance](https://img.shields.io/badge/Behance-0054F7?logo=behance&logoColor=white)](#) ',
        'blender': '[![Blender](https://img.shields.io/badge/Blender-%23F5792A.svg?logo=blender&logoColor=white)](#) ',
        'canva': '[![Canva](https://img.shields.io/badge/Canva-%2300C4CC.svg?&logo=Canva&logoColor=white)](#) ',
        'creative-cloud': '[![Adobe Creative Cloud](https://img.shields.io/badge/Adobe%20Creative%20Cloud-DA1F26?logo=Adobe%20Creative%20Cloud&logoColor=white)](#) ',
        'dribbble': '[![Dribbble](https://img.shields.io/badge/Dribbble-EA4C89?logo=dribbble&logoColor=white)](#) ',
        'figma': '[![Figma](https://img.shields.io/badge/Figma-F24E1E?logo=figma&logoColor=white)](#) ',
        'gimp': '[![Gimp](https://img.shields.io/badge/Gimp-5C5543?logo=gimp&logoColor=white)](#) ',
        'illustrator': '[![Adobe Illustrator](https://img.shields.io/badge/Adobe%20Illustrator-FF9A00?logo=adobe%20illustrator&logoColor=white)](#) ',
        'indesign': '[![Adobe InDesign](https://img.shields.io/badge/Adobe%20InDesign-49021F?logo=adobeindesign&logoColor=white)](#) ',
        'inkscape': '[![Inkscape](https://img.shields.io/badge/Inkscape-000000?logo=Inkscape&logoColor=white)](#) ',
        'krita': '[![Krita](https://img.shields.io/badge/Krita-203759?logo=krita&logoColor=EEF37B)](#) ',
        'lightroom': '[![Adobe Lightroom](https://img.shields.io/badge/Adobe%20Lightroom-31A8FF?logo=Adobe%20Lightroom&logoColor=white)](#) ',
        'photoshop': '[![Adobe Photoshop](https://img.shields.io/badge/Adobe%20Photoshop-31A8FF?logo=Adobe%20Photoshop&logoColor=black)](#) ',
        'premiere-pro': '[![Adobe Premiere Pro](https://img.shields.io/badge/Adobe%20Premiere%20Pro-9999FF?logo=Adobe%20Premiere%20Pro&logoColor=white)](#) ',
        'unsplash': '[![Unsplash](https://img.shields.io/badge/Unsplash-000000?logo=Unsplash&logoColor=white)](#) ',
        'xd': '[![Adobe XD](https://img.shields.io/badge/Adobe%20XD-470137?logo=Adobe%20XD&logoColor=#FF61F6)](#) ',
    },
    'documentation': {
        'docsify': '[![Docsify](https://img.shields.io/badge/Docsify-2ECE53?logo=docsify&logoColor=fff)](#) ',
        'docusaurus': '[![Docusaurus](https://img.shields.io/badge/Docusaurus-3ECC5F?logo=docusaurus&logoColor=fff)](#) ',
        'gitbook': '[![GitBook](https://img.shields.io/badge/GitBook-3884FF?logo=gitbook&logoColor=fff)](#) ',
        'mkdocs': '[![MkDocs](https://img.shields.io/badge/MkDocs-526CFE?logo=materialformkdocs&logoColor=fff)](#) ',
        'read-the-docs': '[![Read the Docs](https://img.shields.io/badge/Read%20the%20Docs-8CA1AF?logo=readthedocs&logoColor=fff)](#) ',
        'sphinx': '[![Sphinx](https://img.shields.io/badge/Sphinx-000?logo=sphinx&logoColor=fff)](#) ',
        'vuepress': '[![VuePress](https://img.shields.io/badge/VuePress-4FC08D?logo=vuedotjs&logoColor=fff)](#) ',
    },
    'education': {
        'codecademy': '[![Codecademy](https://img.shields.io/badge/Codecademy-%2321759B.svg?logo=codecademy&logoColor=white)](#) ',
        'coursera': '[![Coursera](https://img.shields.io/badge/Coursera-0056D2?logo=coursera&logoColor=fff)](#) ',
        'edx': '[![edX](https://img.shields.io/badge/edX-02262B?logo=edx&logoColor=fff)](#) ',
        'freecodecamp': '[![freeCodeCamp](https://img.shields.io/badge/freeCodeCamp-0A0A23?logo=freecodecamp&logoColor=fff)](#) ',
        'khan-academy': '[![Khan Academy](https://img.shields.io/badge/Khan%20Academy-14BF96?logo=khanacademy&logoColor=fff)](#) ',
        'linkedin-learning': '[![LinkedIn Learning](https://img.shields.io/badge/LinkedIn%20Learning-0A66C2?logo=linkedin&logoColor=fff)](#) ',
        'pluralsight': '[![Pluralsight](https://img.shields.io/badge/Pluralsight-F15B2A?logo=pluralsight&logoColor=fff)](#) ',
        'treehouse': '[![Treehouse](https://img.shields.io/badge/Treehouse-5FCF80?logo=treehouse&logoColor=fff)](#) ',
        'udacity': '[![Udacity](https://img.shields.io/badge/Udacity-02B3E4?logo=udacity&logoColor=fff)](#) ',
        'udemy': '[![Udemy](https://img.shields.io/badge/Udemy-A435F0?logo=udemy&logoColor=fff)](#) ',
    },
    'funding': {
        'buymeacoffee': '[![Buy Me a Coffee](https://img.shields.io/badge/Buy%20Me%20a%20Coffee-ffdd00?&logo=buy-me-a-coffee&logoColor=black)](#) ',
        'github-sponsors': '[![Github-Sponsors](https://img.shields.io/badge/Sponsor-30363D?&logo=GitHub-Sponsors&logoColor=#EA4AAA)](#) ',
        'kofi': '[![Ko-fi](https://img.shields.io/badge/Ko--fi-FF5E5B?logo=ko-fi&logoColor=white)](#) ',
        'liberapay': '[![Liberapay](https://img.shields.io/badge/Liberapay-F6C915?logo=liberapay&logoColor=black)](#) ',
        'opencollective': '[![Open Collective](https://img.shields.io/badge/Open%20Collective-3385FF?logo=open-collective&logoColor=white)](#) ',
        'patreon': '[![Patreon](https://img.shields.io/badge/Patreon-F96854?logo=patreon&logoColor=white)](#) ',
        'paypal': '[![PayPal](https://img.shields.io/badge/PayPal-003087?logo=paypal&logoColor=fff)](#) ',
    },
    'framework': {
        '.net': '[![.NET](https://img.shields.io/badge/.NET-512BD4?logo=dotnet&logoColor=fff)](#) ',
        'alpine.js': '[![Alpine.js](https://img.shields.io/badge/Alpine.js-8BC0D0?logo=alpinedotjs&logoColor=fff)](#) ',
        'anaconda': '[![Anaconda](https://img.shields.io/badge/Anaconda-44A833?logo=anaconda&logoColor=fff)](#) ',
        'angular': '[![Angular](https://img.shields.io/badge/Angular-%23DD0031.svg?logo=angular&logoColor=white)](#) ',
        'astro': '[![Astro](https://img.shields.io/badge/Astro-BC52EE?logo=astro&logoColor=fff)](#) ',
        'babel': '[![Babel](https://img.shields.io/badge/Babel-F9DC3E?logo=babel&logoColor=000)](#) ',
        'backbone.js': '[![Backbone.js](https://img.shields.io/badge/Backbone.js-0071B5?logo=backbonedotjs&logoColor=fff)](#) ',
        'bootstrap': '[![Bootstrap](https://img.shields.io/badge/Bootstrap-7952B3?logo=bootstrap&logoColor=fff)](#) ',
        'bun': '[![Bun](https://img.shields.io/badge/Bun-000?logo=bun&logoColor=fff)](#) ',
        'chart.js': '[![Chart.js](https://img.shields.io/badge/Chart.js-FF6384?logo=chartdotjs&logoColor=fff)](#) ',
        'daisyui': '[![DaisyUI](https://img.shields.io/badge/DaisyUI-5A0EF8?logo=daisyui&logoColor=fff)](#) ',
        'deno': '[![Deno](https://img.shields.io/badge/Deno-000?logo=deno&logoColor=fff)](#) ',
        'django': '[![Django](https://img.shields.io/badge/Django-%23092E20.svg?logo=django&logoColor=white)](#) ',
        'electron': '[![Electron](https://img.shields.io/badge/Electron-47848F?logo=electron&logoColor=fff)](#) ',
        'ember': '[![Ember.js](https://img.shields.io/badge/Ember.js-E04E39?logo=emberdotjs&logoColor=fff)](#) ',
        'expo': '[![Expo](https://img.shields.io/badge/Expo-000020?logo=expo&logoColor=fff)](#) ',
        'express': '[![Express.js](https://img.shields.io/badge/Express.js-%23404d59.svg?logo=express&logoColor=%2361DAFB)](#) ',
        'flask': '[![Flask](https://img.shields.io/badge/Flask-000?logo=flask&logoColor=fff)](#) ',
        'flutter': '[![Flutter](https://img.shields.io/badge/Flutter-%2302569B.svg?logo=Flutter&logoColor=white)](#) ',
        'gatsby': '[![Gatsby](https://img.shields.io/badge/Gatsby-%23663399.svg?logo=gatsby&logoColor=white)](#) ',
        'helm': '[![Helm](https://img.shields.io/badge/Helm-0F1689?logo=helm&logoColor=fff)](#) ',
        'hugo': '[![Hugo](https://img.shields.io/badge/Hugo-FF4088?logo=hugo&logoColor=fff)](#) ',
        'jquery': '[![jQuery](https://img.shields.io/badge/jQuery-0769AD?logo=jquery&logoColor=fff)](#) ',
        'kubernetes': '[![Kubernetes](https://img.shields.io/badge/Kubernetes-326CE5?logo=kubernetes&logoColor=fff)](#) ',
        'laravel': '[![Laravel](https://img.shields.io/badge/Laravel-%23FF2D20.svg?logo=laravel&logoColor=white)](#) ',
        'less': '[![Less](https://img.shields.io/badge/Less-1D365D?logo=less&logoColor=fff)](#) ',
        'meteor': '[![Meteor.js](https://img.shields.io/badge/Meteor.js-%23d74c4c.svg?logo=meteor&logoColor=white)](#) ',
        'mocha': '[![Mocha](https://img.shields.io/badge/Mocha-8D6748?logo=mocha&logoColor=fff)](#) ',
        'nest': '[![Nest.js](https://img.shields.io/badge/Nest.js-%23E0234E.svg?logo=nestjs&logoColor=white)](#) ',
        'next': '[![Next.js](https://img.shields.io/badge/Next.js-black?logo=next.js&logoColor=white)](#) ',
        'nodejs': '[![NodeJS](https://img.shields.io/badge/Node.js-6DA55F?logo=node.js&logoColor=white)](#) ',
        'nuxt': '[![Nuxt.js](https://img.shields.io/badge/Nuxt.js-002E3B?logo=nuxtdotjs&logoColor=#00DC82)](#) ',
        'rails': '[![Rails](https://img.shields.io/badge/Rails-%23CC0000.svg?logo=ruby-on-rails&logoColor=white)](#) ',
        'react': '[![React](https://img.shields.io/badge/React-%2320232a.svg?logo=react&logoColor=%2361DAFB)](#) ',
        'react-native': '[![React Native](https://img.shields.io/badge/React_Native-%2320232a.svg?logo=react&logoColor=%2361DAFB)](#) ',
        'redux': '[![Redux](https://img.shields.io/badge/Redux-764ABC?logo=redux&logoColor=fff)](#) ',
        'sass': '[![Sass](https://img.shields.io/badge/Sass-C69?logo=sass&logoColor=fff)](#) ',
        'shadcn/ui': '[![shadcn/ui](https://img.shields.io/badge/shadcn%2Fui-000?logo=shadcnui&logoColor=fff)](#) ',
        'spring-boot': '[![Spring Boot](https://img.shields.io/badge/Spring%20Boot-6DB33F?logo=springboot&logoColor=fff)](#) ',
        'strapi': '[![Strapi](https://img.shields.io/badge/Strapi-%232E7EEA.svg?logo=strapi&logoColor=white)](#) ',
        'symfony': '[![Symfony](https://img.shields.io/badge/Symfony-black?logo=symfony)](#) ',
        'svelte': '[![Svelte](https://img.shields.io/badge/Svelte-%23f1413d.svg?logo=svelte&logoColor=white)](#) ',
        'tailwind': '[![TailwindCSS](https://img.shields.io/badge/Tailwind$20CSS-%2338B2AC.svg?logo=tailwind-css&logoColor=white)](#) ',
        'tauri': '[![Tauri](https://img.shields.io/badge/Tauri-24C8D8?logo=tauri&logoColor=fff)](#) ',
        'three': '[![Three.js](https://img.shields.io/badge/Three.js-000?logo=threedotjs&logoColor=fff)](#) ',
        'vite': '[![Vite](https://img.shields.io/badge/Vite-646CFF?logo=vite&logoColor=fff)](#) ',
        'vue': '[![Vue.js](https://img.shields.io/badge/Vue.js-4FC08D?logo=vuedotjs&logoColor=fff)](#) ',
        'yarn': '[![Yarn](https://img.shields.io/badge/Yarn-2C8EBB?logo=yarn&logoColor=fff)](#) ',
    },
    'game-engine': {
        'amazon-lumberyard': '[![Amazon Lumberyard](https://img.shields.io/badge/Amazon%20Lumberyard-66459B?logo=amazonlumberyard&logoColor=fff)](#) ',
        'construct-3': '[![Construct 3](https://img.shields.io/badge/Construct%203-00FFDA?logo=construct3&logoColor=000)](#) ',
        'cryengine': '[![CryEngine](https://img.shields.io/badge/CryEngine-000?logo=cryengine&logoColor=fff)](#) ',
        'gamemaker': '[![Gamemaker](https://img.shields.io/badge/Gamemaker-000?logo=gamemaker&logoColor=fff)](#) ',
        'godot-engine': '[![Godot Engine](https://img.shields.io/badge/Godot-%23FFFFFF.svg?logo=godot-engine)](#) ',
        'unreal-engine': '[![Unreal Engine](https://img.shields.io/badge/Unreal%20Engine-%23313131.svg?logo=unrealengine&logoColor=white)](#) ',
        'unity': '[![Unity](https://img.shields.io/badge/Unity-%23000000.svg?logo=unity&logoColor=white)](#) '
    },
    'game-stores': {
        'battle-net': '[![Battle.net](https://img.shields.io/badge/Battle.net-%2300AEFF.svg?logo=battle.net&logoColor=white)](#) ',
        'ea': '[![EA](https://img.shields.io/badge/EA-%23000000.svg?logo=ea&logoColor=white)](#) ',
        'epic-games': '[![Epic Games](https://img.shields.io/badge/Epic%20Games-%23313131.svg?logo=epicgames&logoColor=white)](#) ',
        'g2a': '[![G2A](https://img.shields.io/badge/G2A-F05F00?logo=g2a&logoColor=fff)](#) ',
        'gog': '[![GOG.com](https://img.shields.io/badge/GOG.com-86328A?logo=gogdotcom&logoColor=fff)](#) ',
        'humble-bundle': '[![Humble Bundle](https://img.shields.io/badge/Humble%20Bundle-%23494F5C.svg?logo=HumbleBundle&logoColor=white)](#) ',
        'itch-io': '[![Itch.io](https://img.shields.io/badge/itch.io-%23FF0B34.svg?logo=Itch.io&logoColor=white)](#) ',
        'microsoft-store': '[![Microsoft Store](https://img.shields.io/badge/Microsoft%20Store-005FB8?logo=microsoftstore&logoColor=fff)](#) ',
        'nintendo-eshop': '[![Nintendo eShop](https://img.shields.io/badge/Nintendo%20eShop-FF7D00?logo=nintendoswitch&logoColor=fff)](#) ',
        'origin': '[![Origin](https://img.shields.io/badge/Origin-F56C2D?logo=origin&logoColor=fff)](#) ',
        'playstation-store': '[![PlayStation Store](https://img.shields.io/badge/PlayStation%20Store-%230070D1.svg?logo=Playstation&logoColor=white)](#) ',
        'riot-games': '[![Riot Games](https://img.shields.io/badge/Riot%20Games-D32936.svg?logo=riotgames&logoColor=white)](#) ',
        'steam': '[![Steam](https://img.shields.io/badge/Steam-%23000000.svg?logo=steam&logoColor=white)](#) ',
        'uplay': '[![Uplay](https://img.shields.io/badge/Uplay-black?logo=ubisoft)](#) ',
        'xbox-store': '[![Xbox](https://img.shields.io/badge/Xbox%20Store-%23107C10.svg?logo=xbox&logoColor=white)](#) '
    },
    'jobs': {
        'fiverr': '[![Fiverr](https://img.shields.io/badge/Fiverr-1DBF73?logo=fiverr&logoColor=fff)](#) ',
        'glassdoor': '[![Glassdoor](https://img.shields.io/badge/Glassdoor-0CAA41?logo=glassdoor&logoColor=fff)](#) ',
        'indeed': '[![Indeed](https://img.shields.io/badge/Indeed-003A9B?logo=indeed&logoColor=fff)](#) ',
        'linkedin': '[![LinkedIn](https://img.shields.io/badge/LinkedIn-0A66C2?logo=linkedin&logoColor=fff)](#) ',
        'monster': '[![Monster](https://img.shields.io/badge/Monster-6D4C9F?logo=monster&logoColor=fff)](#) ',
        'upwork': '[![Upwork](https://img.shields.io/badge/Upwork-6FDA44?logo=upwork&logoColor=fff)](#) '
    },
    'office': {
        'microsoft': '[![Microsoft](https://img.shields.io/badge/Microsoft-0078D4?logo=microsoft&logoColor=white)](#) ',
        'microsoft-access': '[![Microsoft Access](https://img.shields.io/badge/Microsoft_Access-A4373A?logo=microsoft-access&logoColor=white)](#) ',
        'micorosft-excel': '[![Microsoft Excel](https://img.shields.io/badge/Microsoft_Excel-217346?logo=microsoft-excel&logoColor=white)](#)',
        'microsoft-onedrive': '[![Microsoft OneDrive](https://img.shields.io/badge/Microsoft%20OneDrive-0078D4?logo=microsoftonedrive&logoColor=fff)](#) ',
        'microsoft-onenote': '[![Microsoft OneNote](https://img.shields.io/badge/Microsoft%20OneNote-7719AA?logo=microsoftonenote&logoColor=fff)](#) ',
        'microsoft-outlook': '[![Microsoft Outlook](https://img.shields.io/badge/Microsoft%20Outlook-0078D4?logo=microsoftoutlook&logoColor=fff)](#) ',
        'microsoft-powerpoint': '[![Microsoft PowerPoint](https://img.shields.io/badge/Microsoft_PowerPoint-B7472A?logo=microsoft-powerpoint&logoColor=white)](#) ',
        'microsoft-sharepoint': '[![Microsoft SharePoint](https://img.shields.io/badge/Microsoft_SharePoint-0078D4?logo=microsoft-sharepoint&logoColor=white)](#) ',
        'microsoft-visio': '[![Microsoft Visio](https://img.shields.io/badge/Microsoft_Visio-3955A3?logo=microsoft-visio&logoColor=white)](#) ',
        'microsoft-teams': '[![Microsoft Teams](https://img.shields.io/badge/Microsoft%20Teams-6264A7?logo=microsoftteams&logoColor=fff&)](#) ',
        'microsoft-word': '[![Microsoft Word](https://img.shields.io/badge/Microsoft_Word-2B579A?logo=microsoft-word&logoColor=white)](#) '
    },
    'os': {
        'android': '[![Android](https://img.shields.io/badge/Android-3DDC84?logo=android&logoColor=white)](#) ',
        'almalinux': '[![AlmaLinux](https://img.shields.io/badge/AlmaLinux-000?logo=almalinux&logoColor=fff)](#) ',
        'alpine-linux': '[![Alpine Linux](https://img.shields.io/badge/Alpine%20Linux-0D597F?logo=alpinelinux&logoColor=fff)](#) ',
        'arch-linux': '[![Arch Linux](https://img.shields.io/badge/Arch%20Linux-1793D1?logo=arch-linux&logoColor=fff)](#) ',
        'artix-linux': '[![Artix Linux](https://img.shields.io/badge/Artix%20Linux-10A0CC?logo=artixlinux&logoColor=fff)](#) ',
        'debian': '[![Debian](https://img.shields.io/badge/Debian-A81D33?logo=debian&logoColor=fff)](#) ',
        'fedora': '[![Fedora](https://img.shields.io/badge/Fedora-51A2DA?logo=fedora&logoColor=fff)](#) ',
        'ios': '[![iOS](https://img.shields.io/badge/iOS-000000?&logo=ios&logoColor=white)](#) ',
        'kali-linux': '[![Kali Linux](https://img.shields.io/badge/Kali%20Linux-557C94?logo=kalilinux&logoColor=fff)](#) ',
        'linux': '[![Linux](https://img.shields.io/badge/Linux-FCC624?logo=linux&logoColor=black)](#) ',
        'linux-mint': '[![Linux Mint](https://img.shields.io/badge/Linux%20Mint-87CF3E?logo=linuxmint&logoColor=fff)](#) ',
        'linuxserver': '[![LinuxServer](https://img.shields.io/badge/LinuxServer-DA3B8A?logo=linuxserver&logoColor=fff)](#) ',
        'macos': '[![macOS](https://img.shields.io/badge/macOS-000000?logo=macos&logoColor=F0F0F0)](#) ',
        'manjaro': '[![Manjaro](https://img.shields.io/badge/Manjaro-35BF5C?logo=manjaro&logoColor=fff)](#) ',
        'mx-linux': '[![MX Linux](https://img.shields.io/badge/MX%20Linux-000?logo=mxlinux&logoColor=fff)](#) ',
        'pop!_os': '[![Pop!_OS](https://img.shields.io/badge/Pop!__OS-48B9C7?logo=popos&logoColor=fff)](#) ',
        'rocky-linux': '[![Rocky Linux](https://img.shields.io/badge/Rocky%20Linux-10B981?logo=rockylinux&logoColor=fff)](#) ',
        'ubuntu': '[![Ubuntu](https://img.shields.io/badge/Ubuntu-E95420?logo=ubuntu&logoColor=white)](#) ',
        'void-linux': '[![Void Linux](https://img.shields.io/badge/Void%20Linux-478061?logo=voidlinux&logoColor=fff)](#) ',
        'windows': '[![Windows](https://img.shields.io/badge/Windows-0078D6?logo=windows&logoColor=white)](#) ',
        'windows-10': '[![Windows 10](https://img.shields.io/badge/Windows%2010-0078D6?logo=windows10&logoColor=fff)](#) ',
        'windows-11': '[![Windows 11](https://img.shields.io/badge/Windows%2011-0078D4?logo=windows11&logoColor=fff)](#) ',
        'windows-95': '[![Windows 95](https://img.shields.io/badge/Windows%2095-008080?logo=windows95&logoColor=fff)](#) ',
        'windows-xp': '[![Windows XP](https://img.shields.io/badge/Windows%20XP-039?logo=windowsxp&logoColor=fff)](#) '
    },
    'package-manager': {
        'chocolatey': '[![Chocolatey](https://img.shields.io/badge/Chocolatey-80B5E3?logo=chocolatey&logoColor=fff)](#) ',
        'composer': '[![Composer](https://img.shields.io/badge/Composer-885630?logo=composer&logoColor=fff)](#) ',
        'helm': '[![Helm](https://img.shields.io/badge/Helm-0F1689?logo=helm&logoColor=fff)](#) ',
        'homebrew': '[![Homebrew](https://img.shields.io/badge/Homebrew-FBB040?logo=homebrew&logoColor=fff)](#) ',
        'nix': '[![Nix](https://img.shields.io/badge/Nix-5277C3?logo=nixos&logoColor=fff)](#) ',
        'nuget': '[![NuGet](https://img.shields.io/badge/NuGet-004880?logo=nuget&logoColor=fff)](#) ',
        'npm': '[![npm](https://img.shields.io/badge/npm-CB3837?logo=npm&logoColor=fff)](#) ',
        'pnpm': '[![pnpm](https://img.shields.io/badge/pnpm-F69220?logo=pnpm&logoColor=fff)](#) ',
        'pypi': '[![PyPI](https://img.shields.io/badge/PyPI-3775A9?logo=pypi&logoColor=fff)](#) ',
        'yarn': '[![Yarn](https://img.shields.io/badge/Yarn-2C8EBB?logo=yarn&logoColor=fff)](#) '
    },
    'payment': {
        'apple-pay': '[![Apple Pay](https://img.shields.io/badge/Apple%20Pay-000?logo=applepay&logoColor=fff)](#) ',
        'amazon-pay': '[![Amazon Pay](https://img.shields.io/badge/Amazon%20Pay-F90?logo=amazonpay&logoColor=fff)](#) ',
        'google-pay': '[![Google Pay](https://img.shields.io/badge/Google%20Pay-4285F4?logo=googlepay&logoColor=fff)](#) ',
        'klarna': '[![Klarna](https://img.shields.io/badge/Klarna-FFB3C7?logo=klarna&logoColor=000)](#) ',
        'magento': '[![Magento](https://img.shields.io/badge/Magento-EE672F?logo=magento&logoColor=fff)](#) ',
        'mastercard': '[![MasterCard](https://img.shields.io/badge/MasterCard-EB001B?logo=mastercard&logoColor=fff)](#) ',
        'payoneer': '[![Payoneer](https://img.shields.io/badge/Payoneer-FF4800?logo=payoneer&logoColor=fff)](#) ',
        'paypal': '[![PayPal](https://img.shields.io/badge/PayPal-003087?logo=paypal&logoColor=fff)](#) ',
        'shopify': '[![Shopify](https://img.shields.io/badge/Shopify-7AB55C?logo=shopify&logoColor=fff)](#) ',
        'square': '[![Square](https://img.shields.io/badge/Square-3E4348?logo=square&logoColor=fff)](#) ',
        'stripe': '[![Stripe](https://img.shields.io/badge/Stripe-5851DD?logo=stripe&logoColor=fff)](#) ',
        'visa': '[![Visa](https://img.shields.io/badge/Visa-1A1F71?logo=visa&logoColor=fff)](#) ',
        'woocommerce': '[![WooCommerce](https://img.shields.io/badge/WooCommerce-96588A?logo=woocommerce&logoColor=fff)](#) '
    },
    'programming': {
        'c': '[![C](https://img.shields.io/badge/C-00599C?logo=c&logoColor=white)](#) ',
        'cpp': '[![C++](https://img.shields.io/badge/C++-%2300599C.svg?logo=c%2B%2B&logoColor=white)](#) ',
        'c-sharp': '[![C#](https://img.shields.io/badge/C%23-%23239120.svg?logo=csharp&logoColor=white)](#) ',
        'css': '[![CSS](https://img.shields.io/badge/CSS-1572B6?logo=css3&logoColor=fff)](#) ',
        'dart': '[![Dart](https://img.shields.io/badge/Dart-%230175C2.svg?logo=dart&logoColor=white)](#) ',
        'elixir': '[![Elixir](https://img.shields.io/badge/Elixir-%234B275F.svg?&logo=elixir&logoColor=white)](#) ',
        'flutter': '[![Flutter](https://img.shields.io/badge/Flutter-02569B?logo=flutter&logoColor=fff)](#) ',
        'gnu-bash': '[![GNU Bash](https://img.shields.io/badge/GNU%20Bash-4EAA25?logo=gnubash&logoColor=fff)](#) ',
        'go': '[![Go](https://img.shields.io/badge/Go-%2300ADD8.svg?&logo=go&logoColor=white)](#) ',
        'haskell': '[![Haskell](https://img.shields.io/badge/Haskell-5e5086?logo=haskell&logoColor=white)](#) ',
        'html': '[![HTML](https://img.shields.io/badge/HTML-%23E34F26.svg?logo=html5&logoColor=white)](#) ',
        'htmx': '[![HTMX](https://img.shields.io/badge/%3C/%3E%20HTMX-3D72D7?logo=mysl&logoColor=white)](#) ',
        'java': '[![Java](https://img.shields.io/badge/Java-%23ED8B00.svg?logo=openjdk&logoColor=white)](#) ',
        'javascript': '[![JavaScript](https://img.shields.io/badge/JavaScript-F7DF1E?logo=javascript&logoColor=000)](#) ',
        'json': '[![JSON](https://img.shields.io/badge/JSON-000?logo=json&logoColor=fff)](#) ',
        'kotlin': '[![Kotlin](https://img.shields.io/badge/Kotlin-%237F52FF.svg?logo=kotlin&logoColor=white)](#) ',
        'lua': '[![Lua](https://img.shields.io/badge/Lua-%232C2D72.svg?logo=lua&logoColor=white)](#) ',
        'markdown': '[![Markdown](https://img.shields.io/badge/Markdown-%23000000.svg?logo=markdown&logoColor=white)](#) ',
        'mdx': '[![MDX](https://img.shields.io/badge/MDX-1B1F24?logo=mdx&logoColor=fff)](#) ',
        'nim': '[![Nim](https://img.shields.io/badge/Nim-%23FFE953.svg?&logo=nim&logoColor=white)](#) ',
        'nix': '[![Nix](https://img.shields.io/badge/Nix-5277C3.svg?&logo=NixOS&logoColor=white)](#) ',
        'objective-c': '[![Objective-C](https://img.shields.io/badge/OBJECTIVE--C-%233A95E3.svg?&logo=apple&logoColor=white)](#) ',
        'perl': '[![Perl](https://img.shields.io/badge/Perl-%2339457E.svg?logo=perl&logoColor=white)](#) ',
        'php': '[![PHP](https://img.shields.io/badge/php-%23777BB4.svg?&logo=php&logoColor=white)](#) ',
        'powershell': '[![PowerShell](https://img.shields.io/badge/PowerShell-%235391FE.svg?logo=powershell&logoColor=white)](#) ',
        'python': '[![Python](https://img.shields.io/badge/Python-3776AB?logo=python&logoColor=fff)](#) ',
        'r': '[![R](https://img.shields.io/badge/R-%23276DC3.svg?logo=r&logoColor=white)](#) ',
        'ruby': '[![Ruby](https://img.shields.io/badge/Ruby-%23CC342D.svg?&logo=ruby&logoColor=white)](#) ',
        'rust': '[![Rust](https://img.shields.io/badge/Rust-%23000000.svg?e&logo=rust&logoColor=white)](#) ',
        'sass': '[![Sass](https://img.shields.io/badge/Sass-C69?logo=sass&logoColor=fff)](#) ',
        'scala': '[![Scala](https://img.shields.io/badge/Scala-%23DC322F.svg?logo=scala&logoColor=white)](#) ',
        'swift': '[![Swift](https://img.shields.io/badge/Swift-F54A2A?logo=swift&logoColor=white)](#) ',
        'typescript': '[![TypeScript](https://img.shields.io/badge/TypeScript-3178C6?logo=typescript&logoColor=fff)](#) ',
        'zig': '[![Zig](https://img.shields.io/badge/Zig-F7A41D?logo=zig&logoColor=fff)](#) '
    },
    'restaurant': {
        'burger-king': '[![Burger King](https://img.shields.io/badge/Burger%20King-D62300?logo=burgerking&logoColor=fff)](#) ',
        'kfc': '[![KFC](https://img.shields.io/badge/KFC-F40027?logo=kfc&logoColor=white)](#) ',
        'mcdonalds': '[![McDonalds](https://img.shields.io/badge/McDonald%27s-FBC817?logo=McDonald%27s&logoColor=white)](#) ',
        'taco-bell': '[![Taco Bell](https://img.shields.io/badge/Taco%20Bell-38096C?logo=tacobell&logoColor=fff)](#) ',
    },
    'review': {
        'g2': '[![G2](https://img.shields.io/badge/G2-FF492C?logo=g2&logoColor=fff)](#) ',
        'glassdoor': '[![Glassdoor](https://img.shields.io/badge/Glassdoor-00A162?logo=glassdoor&logoColor=fff)](#) ',
        'trustpiolot': '[![Trustpilot](https://img.shields.io/badge/Trustpilot-00B67A?logo=trustpilot&logoColor=fff)](#) ',
        'yelp': '[![Yelp](https://img.shields.io/badge/Yelp-FF1A1A?logo=yelp&logoColo=fff)](#)'
    },
    'search-engine': {
        'aol': '[![AOL](https://img.shields.io/badge/AOL-39F?logo=aol&logoColor=fff)](#) ',
        'baidu': '[![Baidu](https://img.shields.io/badge/Baidu-2319DC?logo=baidu&logoColor=white)](#) ',
        'bing': '[![Bing](https://img.shields.io/badge/Bing-258FFA?logo=microsoftbing&logoColor=fff)](#) ',
        'duckduckgo': '[![DuckDuckGo](https://img.shields.io/badge/DuckDuckGo-FF5722?logo=duckduckgo&logoColor=white)](#) ',
        'google': '[![Google](https://img.shields.io/badge/Google-4285F4?logo=google&logoColor=white)](#) '
    },
    'social': {
        'anilist': '[![AniList](https://img.shields.io/badge/AniList-02A9FF?logo=anilist&logoColor=fff)](#) ',
        'bluesky': '[![Bluesky](https://img.shields.io/badge/Bluesky-0285FF?logo=bluesky&logoColor=fff)](#) ',
        'deviantart': '[![DeviantArt](https://img.shields.io/badge/DeviantArt-05CC47?logo=deviantart&logoColor=fff)](#) ',
        'discord': '[![Discord](https://img.shields.io/badge/Discord-%235865F2.svg?&logo=discord&logoColor=white)](#) ',
        'facebook': '[![Facebook](https://img.shields.io/badge/Facebook-%231877F2.svg?logo=Facebook&logoColor=white)](#) ',
        'flickr': '[![Flickr](https://img.shields.io/badge/Flickr-0063DC?logo=flickr&logoColor=fff)](#) ',
        'github': '[![GitHub](https://img.shields.io/badge/GitHub-%23121011.svg?logo=github&logoColor=white)](#) ',
        'gmail': '[![Gmail](https://img.shields.io/badge/Gmail-D14836?logo=gmail&logoColor=white)](#) ',
        'guilded': '[![Guilded](https://img.shields.io/badge/Guilded-F5C400?logo=guilded&logoColor=000)](#) ',
        'instagram': '[![Instagram](https://img.shields.io/badge/Instagram-%23E4405F.svg?logo=Instagram&logoColor=white)](#) ',
        'kick': '[![Kick](https://img.shields.io/badge/Kick-53FC19?logo=kick&logoColor=000)](#) ',
        'leetcode': '[![LeetCode](https://img.shields.io/badge/LeetCode-000000?logo=LeetCode&logoColor=#d16c06)](#) ',
        'linktree': '[![LinkTree](https://img.shields.io/badge/LinkTree-1de9b6?logo=linktree&logoColor=white)](#) ',
        'linkedin': '[![LinkedIn](https://img.shields.io/badge/Linkedin-%230077B5.svg?logo=linkedin&logoColor=white)](#) ',
        'matrix': '[![Matrix](https://img.shields.io/badge/Matrix-000?logo=matrix&logoColor=fff)](#) ',
        'medium': '[![Medium](https://img.shields.io/badge/Medium-black?logo=medium&logoColor=white)](#) ',
        'messenger': '[![Messenger](https://img.shields.io/badge/Messenger-00B2FF?logo=messenger&logoColor=white)](#) ',
        'outlook': '[![Outlook](https://img.shields.io/badge/Microsoft_Outlook-0078D4?logo=microsoft-outlook&logoColor=white)](#) ',
        'mal': '[![MyAnimeList](https://img.shields.io/badge/MyAnimeList-2E51A2?logo=myanimelist&logoColor=fff)](#) ',
        'pinterest': '[![Pinterest](https://img.shields.io/badge/Pinterest-%23E60023.svg?logo=Pinterest&logoColor=white)](#) ',
        'pixiv': '[![Pixiv](https://img.shields.io/badge/pixiv-%2300ADD8.svg?logo=pixiv&logoColor=white)](#) ',
        'proton-mail': '[![Proton Mail](https://img.shields.io/badge/Proton%20Mail-6D4AFF?logo=protonmail&logoColor=fff)](#) ',
        'reddit': '[![Reddit](https://img.shields.io/badge/Reddit-FF4500?logo=reddit&logoColor=white)](#) ',
        'slack': '[![Slack](https://img.shields.io/badge/Slack-purple?logo=slack&logoColor=white)](#) ',
        'snapchat': '[![Snapchat](https://img.shields.io/badge/Snapchat-%23FFFC00.svg?logo=Snapchat&logoColor=white)](#) ',
        'spotify': '[![Spotify](https://img.shields.io/badge/Spotify-1ED760?logo=spotify&logoColor=white)](#) ',
        'stackoverflow': '[![Stack Overflow](https://img.shields.io/badge/-StackOverflow-FE7A16?logo=stack-overflow&logoColor=white)](#) ',
        'teamspeak': '[![TeamSpeak](https://img.shields.io/badge/TeamSpeak-2580C3?logo=teamspeak&logoColor=white)](#) ',
        'telegram': '[![Telegram](https://img.shields.io/badge/Telegram-2CA5E0?logo=telegram&logoColor=white)](#) ',
        'threads': '[![Threads](https://img.shields.io/badge/Threads-000000?logo=Threads&logoColor=white)](#) ',
        'tiktok': '[![TikTok](https://img.shields.io/badge/TikTok-black?logo=tiktok&logoColor=white)](#) ',
        'tumblr': '[![Tumblr](https://img.shields.io/badge/Tumblr-36465D?logo=tumblr&logoColor=fff)](#) ',
        'twitch': '[![Twitch](https://img.shields.io/badge/Twitch-%239146FF.svg?logo=Twitch&logoColor=white)](#) ',
        'twitter': '[![Twitter](https://img.shields.io/badge/Twitter-%231DA1F2.svg?logo=Twitter&logoColor=white)](#) ',
        'wechat': '[![WeChat](https://img.shields.io/badge/WeChat-07C160?logo=wechat&logoColor=white)](#) ',
        'whatsapp': '[![WhatsApp](https://img.shields.io/badge/WhatsApp-25D366?logo=whatsapp&logoColor=white)](#) ',
        'x': '[![X](https://img.shields.io/badge/X-%23000000.svg?logo=X&logoColor=white)](#) ',
        'xbox-app': '[![Xbox App](https://img.shields.io/badge/Xbox%20App-%23107C10.svg?logo=Xbox&logoColor=white)](#) ',
        'youtube': '[![YouTube](https://img.shields.io/badge/YouTube-%23FF0000.svg?logo=YouTube&logoColor=white)](#) ',
        'zoom': '[![Zoom](https://img.shields.io/badge/Zoom-2D8CFF?logo=zoom&logoColor=white)](#) '
    },
    'sound': {
        'apple-music': '[![Apple Music](https://img.shields.io/badge/Apple%20Music-F34E68?logo=apple%20music&logoColor=white)](#) ',
        'apple-podcasts': '[![Apple Podcasts](https://img.shields.io/badge/Apple_Podcasts-9933CC?logo=apple-podcasts&logoColor=white)](#) ',
        'audacity': '[![Audacity](https://img.shields.io/badge/Audacity-0000CC?logo=audacity&logoColor=white)](#) ',
        'google-podcasts': '[![Google Podcasts](https://img.shields.io/badge/Google_Podcasts-4285F4?logo=google-podcasts&logoColor=white)](#) ',
        'lastfm': '[![LastFM](https://img.shields.io/badge/last.fm-D51007?logo=last.fm&logoColor=white)](#) ',
        'pandora': '[![Pandora](https://img.shields.io/badge/Pandora-3668FF?logo=pandora)](#) ',
        'shazam': '[![Shazam](https://img.shields.io/badge/Shazam-0088FF?logo=Shazam&logoColor=white)](#) ',
        'soundcloud': '[![Soundcloud](https://img.shields.io/badge/Soundcloud-FF3300?logo=Soundcloud&logoColor=white)](#) ',
        'spotify': '[![Spotify](https://img.shields.io/badge/Spotify-1ED760?logo=spotify&logoColor=white)](#) ',
        'tidal': '[![Tidal](https://img.shields.io/badge/Tidal-000000?logo=Tidal&logoColor=white)](#) ',
        'tunein': '[![TuneIn](https://img.shields.io/badge/TuneIn-14D8CC?logo=TuneIn&logoColor=white)](#) ',
        'youtube-music': '[![YouTube Music](https://img.shields.io/badge/YouTube_Music-FF0000?logo=youtube-music&logoColor=white)](#) '
    },
    'static-site': {
        'docusaurus': '[![Docusaurus](https://img.shields.io/badge/Docusaurus-3ECC5F?logo=docusaurus&logoColor=fff)](#) ',
        'eleventy': '[![Eleventy](https://img.shields.io/badge/Eleventy-black?logo=eleventy)](#) ',
        'gatsby': '[![Gatsby](https://img.shields.io/badge/Gatsby-%23663399.svg?logo=gatsby&logoColor=white)](#) ',
        'gridsome': '[![Gridsome](https://img.shields.io/badge/Gridsome-00A672?logo=gridsome&logoColor=fff)](#) ',
        'hexo': '[![Hexo](https://img.shields.io/badge/Hexo-0E83CD?logo=hexo&logoColor=fff)](#) ',
        'hugo': '[![Hugo](https://img.shields.io/badge/Hugo-FF4088?logo=hugo&logoColor=fff)](#) ',
        'jekyll': '[![Jekyll](https://img.shields.io/badge/Jekyll-C00?logo=jekyll&logoColor=fff)](#) ',
        'mkdocs': '[![MkDocs](https://img.shields.io/badge/MkDocs-526CFE?logo=materialformkdocs&logoColor=fff)](#) ',
        'nuxt': '[![Nuxt.js](https://img.shields.io/badge/Nuxt.js-00DC82?logo=nuxtdotjs&logoColor=fff)](#) ',
        'pelican': '[![Pelican](https://img.shields.io/badge/Pelican-14A0C4?logo=pelican&logoColor=fff)](#) '
    },
    'video-streaming': {
        'amazon-prime': '[![Amazon Prime](https://img.shields.io/badge/Amazon%20Prime-0F79AF?logo=amazonprime&logoColor=white)](#) ',
        'apple-tv': '[![Apple TV](https://img.shields.io/badge/Apple%20TV-000000?logo=Apple%20TV&logoColor=white)](#) ',
        'crunchyroll': '[![Crunchyroll](https://img.shields.io/badge/Crunchyroll-F47521?logo=crunchyroll&logoColor=white)](#) ',
        'hulu': '[![Hulu](https://img.shields.io/badge/Hulu-1CE783?logo=hulu&logoColor=white)](#) ',
        'netflix': '[![Netflix](https://img.shields.io/badge/Netflix-E50914?logo=netflix&logoColor=white)](#) ',
        'roku': '[![Roku](https://img.shields.io/badge/Roku-6f1ab1?logo=roku&logoColor=white)](#) '
    },
    'vr': {
        'arkit': '[![ARKit](https://img.shields.io/badge/ARKit-%23000000.svg?logo=apple&logoColor=white)](#) ',
        'google-cardboard': '[![Google Cardboard](https://img.shields.io/badge/Google%20Cardboard-%23FF713B.svg?logo=google-cardboard&logoColor=white)](#) ',
        'oculus': '[![Oculus](https://img.shields.io/badge/Oculus-%231A1A1A.svg?logo=oculus&logoColor=white)](#) ',
        'psvr': '[![PlayStation VR](https://img.shields.io/badge/PlayStation%20VR-%23007ACC.svg?logo=playstation&logoColor=white)](#) ',
        'steamvr': '[![SteamVR](https://img.shields.io/badge/SteamVR-%23232F3E.svg?logo=steam&logoColor=white)](#) '
    }
};

module.exports = badges;